services:
  http_drupal:
    image: httpd:latest
    container_name: nage-libre_http_drupal
    restart: unless-stopped
    ports:
      - "80:80"
    hostname: nage-libre.dok
    volumes:
      - ${SOURCES_DRUPAL}:/var/www/nage-libre-drupal:rw
      - ./volumes/web-nage-libre-logs/:/var/log/apache2:rw
      - ./config/apache2/httpd_drupal.conf:/usr/local/apache2/conf/httpd.conf:rw
    networks:
      - default
  
  http_drupal_10:
    image: httpd:latest
    container_name: nage-libre_http_drupal_10
    restart: unless-stopped
    ports:
      - "8080:80"
    hostname: nage-libre-10.dokZ
    volumes:
      - ${SOURCES_DRUPAL_10}:/var/www/nage-libre-drupal-10:rw
      - ./volumes/web-nage-libre-10-logs/:/var/log/apache2:rw
      - ./config/apache2/httpd_drupal_10.conf:/usr/local/apache2/conf/httpd.conf:rw
    networks:
      - default

  php8:
    container_name: nage-libre_php8
    build:
      dockerfile: ./dockerfiles/php8/dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "9002:9000"
    volumes:
      - ${SOURCES_DRUPAL_10}:/var/www/nage-libre-drupal-10:rw
      - ./volumes/web-nage-libre-10-logs:/var/log:rw
      - ./config/php8/php.ini:/etc/php/8.4/fpm/conf.d/90-custom.ini:rw
    networks:
      - default

  php7:
    container_name: nage-libre_php7
    build:
      dockerfile: ./dockerfiles/php7/dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - ${SOURCES_DRUPAL}:/var/www/nage-libre-drupal:rw
      - ./volumes/web-nage-libre-logs:/var/log:rw
      - ./config/php7/php.ini:/usr/local/etc/php/7.4/fpm/php.ini:rw
    networks:
      - default

  mariadb:
    container_name: nage-libre_db
    image: mariadb:latest
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/nage-libre_db:/var/lib/mysql:rw
      - ./config/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf:rw
      - ./config/mariadb/init.sql:/data/application/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file=/data/application/init.sql
    networks:
      - default

  mysql8:
    container_name: nage-libre_db_mysql8
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nagelibre10
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/nage-libre_db_mysql8:/var/lib/mysql:rw
      - ./config/mysql8/mysql8.cnf:/etc/mysql/conf.d/mysql8.cnf:rw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    networks:
      - default

networks:
  default:
    driver: bridge